ecom_project/ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import  settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('login_app.urls')),
    path('',include('store_app.urls')),
    path('shop/',include('order_app.urls')),
    path('payment/',include('payment_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom_project/login_app/urls.py
from django.urls import path 
from . import views
app_name = 'login_app'



urlpatterns = [
    path('',views.signup_user,name='signup'),  
    path('sign_up/',views.signup_user,name='signup'), 
    path('login/',views.login_user,name='login'), 
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.user_profile,name='user_profile'),  
]

ecom_project/order_app/urls.py
from django.urls import path
from . import views
app_name = "order_app"

urlpatterns = [
    path('add_to_cart/<pk>/',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart_view,name='cart'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
]

ecom_project/payment_app/urls.py
from django.urls import path
from . import views
app_name = 'payment_app'
urlpatterns = [
    
    path('checkout/',views.checkout,name='checkout'),
    path('payment/',views.payment,name='payment'),
    path('complete/',views.complete,name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="order"),
]

ecom_project/store_app/urls.py
from django.urls import path

from . import views 

app_name = 'store_app'



urlpatterns = [
        path('',views.home.as_view(),name='home'),
        path('product/<pk>/', views.Product_detail.as_view(), name='product_detail'),
]

ecom_project/templates/order_templates/cart.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-5">
  <div class="my-5">
    <h2>Your Cart</h2>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col" width="15%">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Product image</th>
        <th scope="col">Quantity</th>
        <th scope="col" align="right">Price</th>
        <th scop="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for cart in carts %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{cart.item.name}}</td>
        <td><img src="/media/{{cart.item.main_image}}" alt="" border=3 height=50 width=100></img></td>
        <td>
          <a class="mr-2" href="{% url 'order_app:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
          {{ cart.quantity }}
          <a class="mr-2" href="{% url 'order_app:increase' pk=cart.item.pk %}"> <span class="badge badge-light"> <i class="fas fa-plus"></i></span></a>
        </td>
        <td align="right">&#2547; {{cart.get_total}}</td>
        <td><a href="{% url 'order_app:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove From Cart</a></td>
      </tr>
      {% endfor %}
      <tr>
        <th scope="row"></th>
        <td colspan="2">Total</td>
        <td align="right">&#2547; {{order.get_totals | floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td colspan="4" class="text-right">
          <a href="{% url 'store_app:home' %}" class="btn btn-warning mr-4">Continue Shoping</a>
          <a href="{% url 'payment_app:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}