ecom_project/ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import  settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('login_app.urls')),
    path('',include('store_app.urls')),
    path('shop/',include('order_app.urls')),
    path('payment/',include('payment_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom_project/login_app/urls.py
from django.urls import path 
from . import views
app_name = 'login_app'



urlpatterns = [
    path('',views.signup_user,name='signup'),  
    path('sign_up/',views.signup_user,name='signup'), 
    path('login/',views.login_user,name='login'), 
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.user_profile,name='user_profile'),  
]

ecom_project/payment_app/urls.py
from django.urls import path
from . import views
app_name = 'payment_app'
urlpatterns = [
    
    path('checkout/',views.checkout,name='checkout'),
    path('payment/',views.payment,name='payment'),
    path('complete/',views.complete,name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="order"),
]

ecom_project/store_app/urls.py
from django.urls import path

from . import views 

app_name = 'store_app'



urlpatterns = [
        path('',views.home.as_view(),name='home'),
        path('product/<pk>/', views.Product_detail.as_view(), name='product_detail'),
]

ecom_project/templates/payment_templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5">
  <h2 class="mb-3">
    Shipping Address 
  </h2>
  <div class="row">
    <div class="col-md-9">
      <div class="card mb-5" style="height: auto">
        <div class="card-body">
          <form method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary float-right">Save Address</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card" style="height:auto">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            {% for order_item in order_items %}
            <img src="/media/{{order_item.item.main_image}}" height=100 width=100 alt="">
              <li class="list-group-item">{{ order_item.item.name}} x {{order_item.quantity}}</li>
            {% endfor %}
          </ul>
        </div>
        <div class="card-footer">
          <span class="float-left"><b>Order Total</b></span>
          <span class="float-right"><b>&#2547; {{order_total|floatformat:2}}</b></span>
        </div>
      </div>
      <br>
      <br>
      {% if saved_address.is_fully_filled %}
      <a href="{% url 'payment_app:payment' %}" class="btn btn-warning btn-md">Proceed to Payment</a>
      {% else %}
      <div class="alert alert-info">
        <p>Please fill up all the information to make payment.</p>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

ecom_project/templates/payment_templates/complete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="5; url={% url 'store_app:home' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Payment Status</title>
</head>
<body>
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</body>
</html>

ecom_project/templates/payment_templates/order.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
  <h2 class="text-center"><strong>Your Orders</strong></h2>
  <div class="row">
    <div class="col-md-12">
      <div class="card mt-5" style="height:auto">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Order Id</th>
                <th scope="col">Products</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="#">{{ order.order_id }}</a></td>
                <td>
                  {% for item in order.orderitem.all %} {{item}} <br> {% endfor %}
                </td>
                <td><span class="badge badge-primary">Processing Your Order</span></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-12 my-5 text-center">
      <a href="{% url 'store_app:home' %}">Back to Home</a>
    </div>
  </div>
</div>
{% endblock %}