ecom_project/ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import  settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('login_app.urls')),
    path('',include('store_app.urls')),
    path('shop/',include('order_app.urls')),
    path('payment/',include('payment_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom_project/login_app/urls.py
from django.urls import path 
from . import views
app_name = 'login_app'



urlpatterns = [
    path('',views.signup_user,name='signup'),  
    path('sign_up/',views.signup_user,name='signup'), 
    path('login/',views.login_user,name='login'), 
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.user_profile,name='user_profile'),  
]

ecom_project/templates/login_templates/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block content %}

<h2 class="py-5">
   Edit  Profile Information
</h2>
<form action="" method="POST" class="form-group">

    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success" name="button">Change</button>

</form>



{% endblock %}

ecom_project/templates/login_templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block content %}

<h2 class="py-5">
    Log in to your account
</h2>
<form action="" method="POST" class="form-group">

    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success" name="button">Log in</button>

</form>

<p>Don't have an account? Sign up  <a href="{% url 'login_app:signup' %}">here</a></p>

{% endblock %}

ecom_project/templates/login_templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block content %}

<h2 class="py-5">
    Create New Account
</h2>
<form action="" method="POST" class="form-group">

    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success" name="button">Create Account</button>
</form>
<p>Already an user? Log in <a href="{% url 'login_app:login' %}">here</a></p>

{% endblock %}